---
- name: retrieving and changing bridge Gaia Interfaces
  hosts: gw_3
  connection: httpapi
  gather_facts: false
  collections:
    - check_point.gaia
  vars:
    - interface_name: br1
  tasks:
    - name: Show bridge interface by specifying its name
      cp_gaia_bridge_interface_facts:
        name: "{{ interface_name }}"
      register: bridge_details

    - name: print original interface details
      debug:
        msg: "{{ bridge_details['ansible_facts'] }}"

    - name: Configure the interface
      cp_gaia_bridge_interface:
        name: "{{ interface_name }}"
        ipv4_address: 10.5.5.55
        ipv4_mask_length: 24
        enabled: false
        comments: Set via Ansible
        ipv6_address:
        ipv6_autoconfig: false
        ipv6_mask_length:
        mtu: 1500
        # Bridge Settings
        members:
          - eth5
          - eth6
        # Get IPv4 from a DHCP server
        dhcp: {
            enabled: true,
            # default is 60
            server_timeout: 60,
            # default is 300
            retry: 300,
            leasetime: 900,
            # default is 10
            reacquire_timeout: 10,
          }
      register: updated_interface_details

    - name: print new interface details if changed
      debug:
        msg: "{{ updated_interface_details }}"
      when: updated_interface_details['changed'] == true
