---
- name: retreiving the Gaia active Kernel Routes
  hosts: gw_3
  connection: httpapi
  gather_facts: false
  collections:
    - check_point.gaia
  tasks:
    - name: get the kernel routes
      cp_gaia_routes_kernel_facts:
        # default 50
        limit: 20
        # Default 0
        offset: 0
        # ASC or DESC
        order: DESC
      register: kernel_routes

    - name: print the kernel routes
      debug:
        msg: "{{ kernel_routes['ansible_facts'] }}"
