---
- name: retrieving and changing the Gaia scheduled jobs  (Supported starting Gaia API V1.7)
  hosts: gw_3
  connection: httpapi
  gather_facts: false
  collections:
    - check_point.gaia

  tasks:
    - name: get the existing scheduled job settings
      cp_gaia_scheduled_job_facts:
      register: original_scheduled_job_settings

    - name: print original scheduled job details
      debug:
        msg: "{{ original_scheduled_job_settings }}"

    - name: Add new scheduled job
      cp_gaia_scheduled_job:
        state: present
        name: "weekly_job"
        command: "/home/admin/job.sh"

        recurrence: {
            # Options: 'system-startup', 'interval', 'hourly', 'daily', 'weekly', 'monthly'
            type: "monthly",
            interval: 10,
            # Time of day in 24 hour format. Relevant for "daily", "weekly" and "monthly" recurrence types.
            time_of_day: { hour: 10, minute: 30 },
            # Hours of day in 24 hour format. Can choose multiple hours. Relevant for "hourly" recurrence type.
            hourly: { hours_of_day: 11, minute: 11 },
            # Days of the week. Relevant for "weekly" recurrence type.
            # weekdays: [],
            # Days of the month. Relevant for "monthly" recurrence type.
            days: [2, 16],
            # Month numbers. Relevant for "monthly" recurrence type.
            months: [1, 3, 6, 9, 12],
          }

    - name: print new scheduled job settings
      debug:
        msg: "{{ new_scheduled_job_settings }}"
      when: new_scheduled_job_settings['changed'] == true

    - name: Show scheduled job mail
      check_point.gaia.cp_gaia_scheduled_job_mail_facts:
      register: original_scheduled_job_email_settings

    - name: print original scheduled job Email details
      debug:
        msg: "{{ original_scheduled_job_email_settings }}"

    - name: Set scheduled job mail
      cp_gaia_scheduled_job_mail:
        email_address: "sysadmins@company.com"
      register: new_scheduled_job_email_settings

    - name: print new scheduled job Email details
      debug:
        msg: "{{ new_scheduled_job_email_settings }}"
