---
- name: retreiving and changing the Gaia scheduled Snapshot
  hosts: gw_1
  connection: httpapi
  gather_facts: false
  collections:
    - check_point.gaia
  tasks:
    - name: get the existing scheduled snapshot settings
      cp_gaia_scheduled_snapshot_facts:
      register: original_scheduled_snapshot_settings

    - name: print original scheduled snapshot details
      debug:
        msg: "{{ original_scheduled_snapshot_settings['ansible_facts'] }}"

    - name: Set scheduled snapshot
      cp_gaia_scheduled_snapshot:
        enabled: True
        name_prefix: "weekly_snap"
        # description allow 15 characters max.
        description: "weekly_snaps"
        # Destination in the Gaia Portal
        host: {
            # supported target: 'lvm', 'ftp', 'scp'
            target: "lvm",
          }
        #username: "admin",
        # Path must end with a slash!
        #upload_path: /var/log/snapshots/,
        #password: Cpwins!1,
        #ip_address: 203.0.113.125,
        recurrence: {
            # Options: 'daily', 'monthly', 'weekly'
            pattern: "weekly",
            months: [],
            weekdays: ["Mon", "Wed"],
            days: [],
            time: { "minute": 30, "hour": 13 },
          }
        retention_policy: {
            # should be above what's kept for backup in LVM
            keep_disk_space_above_in_GB: 26,
            min_snapshots_to_keep: 1,
            max_snapshots_to_keep: 3,
          }
      register: new_scheduled_snapshot_settings

    - name: print new scheduled snapshot  details
      debug:
        msg: "{{ new_scheduled_snapshot_settings }}"
