---
- name: retreiving and changing the Gaia SSH Server settings  (Supported starting Gaia API V1.7)
  hosts: gw_3
  connection: httpapi
  gather_facts: false
  collections:
    - check_point.gaia
  tasks:
    - name: get the existing SSH Server settings
      cp_gaia_ssh_server_settings_facts:
      register: original_ssh_server_settings

    - name: print original proxy details
      debug:
        msg: "{{ original_ssh_server_settings }}"

    - name: Set ssh server settings
      check_point.gaia.cp_gaia_ssh_server_settings:
        enabled_ciphers:
          [
            "aes128-ctr",
            "aes128-gcm@openssh.com",
            "aes192-ctr",
            "aes256-ctr",
            "aes256-gcm@openssh.com",
            "chacha20-poly1305@openssh.com",
          ]
        enabled_kex_algorithms:
          [
            "curve25519-sha256",
            "curve25519-sha256@libssh.org",
            "diffie-hellman-group14-sha1",
            "diffie-hellman-group14-sha256",
            "diffie-hellman-group16-sha512",
            "diffie-hellman-group18-sha512",
            "diffie-hellman-group-exchange-sha256",
            "ecdh-sha2-nistp256",
            "ecdh-sha2-nistp384",
            "ecdh-sha2-nistp521",
          ]
        enabled_mac_algorithms:
          [
            "hmac-sha1",
            "hmac-sha1-etm@openssh.com",
            "hmac-sha2-256",
            "hmac-sha2-256-etm@openssh.com",
            "hmac-sha2-512",
            "hmac-sha2-512-etm@openssh.com",
            "umac-64-etm@openssh.com",
            "umac-64@openssh.com",
            "umac-128-etm@openssh.com",
            "umac-128@openssh.com",
          ]

      register: new_ssh_server_settings

    - name: print new ssh server settings
      debug:
        msg: "{{ new_ssh_server_settings }}"
      when: new_ssh_server_settings['changed'] == true
