---
- name: retreiving and changing the Gaia VLAN Interfaces
  hosts: gw_3
  connection: httpapi
  gather_facts: false
  collections:
    - check_point.gaia
  vars:
    - interface_name: eth8.12
  tasks:
    - name: Show VLAN interface by specifying its name
      cp_gaia_vlan_interface_facts:
        name: "{{ interface_name }}"
      register: interface_details

    - name: print original interface details
      debug:
        msg: "{{ interface_details['ansible_facts'] }}"

    - name: Configure the VLAN interface
      cp_gaia_vlan_interface:
        state: present
        name: "{{ interface_name }}"
        enabled: false
        comments: set via Ansible
        ipv4_address:
        ipv4_mask_length:
        ipv6_address:
        ipv6_autoconfig: false
        ipv6_mask_length:

        mtu: 1500
        # Get IPv4 from a DHCP server
        dhcp: {
            enabled: true,
            # default is 60
            server_timeout: 60,
            # default is 300
            retry: 300,
            leasetime: 900,
            # default is 10
            reacquire_timeout: 10,
          }
      register: updated_interface_details

    - name: print new interface details if changed
      debug:
        msg: "{{ updated_interface_details }}"
      when: updated_interface_details['changed'] == true
