---
- name: "create a policy package"
  check_point.mgmt.cp_mgmt_package: 
    name: "external_gw_policy_package"
    color: "cyan"
    access: "true"
    threat_prevention: "true"
    state: present
  register: policy_package_results
  notify: Publish Handler 

- name: showpolicy package results
  debug: 
    msg: "{{ policy_package_results }}"
...
