- name: Check Point Access Layers
  connection: httpapi
  hosts: checkpoint_mgmt
  gather_facts: false
  collections:
  - check_point.mgmt
  vars:
    state: present
    ansible_checkpoint_domain: "Ottawa"
  tasks:
    - name: Task for New_Service_1
      cp_mgmt_service_other:
        name: New_Service_1
        ip_protocol: 51
        accept_replies: false
        override_default_settings: false
        session_timeout: 0
        use_default_session_timeout: true
        match_for_any: true
        sync_connections_on_cluster: true
        aggressive_aging:
          enable: true
          timeout: 360
          use_default_timeout: false
          default_timeout: 0
        keep_connections_open_after_policy_installation: false
        comments: ''
        color: black
        tags: []
        state: '{{state}}'
        ignore_warnings: false
        ignore_errors: false
        wait_for_task: true
        wait_for_task_timeout: '30'

    - name: publish the session
      cp_mgmt_publish: